environment:
  nodejs_version: "8"
  SKALE_WORKERS: "2"
  SKALE_MEMORY: "512"
  AWS_ACCESS_KEY_ID:
    secure: hWClEdeW0r+5qRWcF0Ez7nGmqkKbfdHLlxsw3x1wvhE=
  AWS_SECRET_ACCESS_KEY:
    secure: 8YMyTcupMmcUho/Z9Hn1QlT9qs12SNs6xi9upsHXCM00r7aWNiUUTIF4qy2rza7R

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run tape

build: off
