site_name: Skale
site_description: Skale documentation
site_favicon: 'images/favicon.png'
dev_addr: 0.0.0.0:8000

docs_dir: docs
theme: 'material'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra:
  logo: 'images/logo.svg'

pages:
  - About Skale: 'index.md'
  - Programming guide:
    - 'concepts.md'
    - 'skale-API.md'
    - 'machine-learning.md'
  - 'skale-hackers-guide.md'

repo_url: https://github.com/skale-me/skale-engine/
google_analytics: ['UA-75822605-1', 'skale-engine.github.io']
