# Project information
site_name: Skale
site_description: Skale documentation
site_author: 'Marc Vertes'
site_url: 'https://skale-me.github.io/skale/'
dev_addr: 0.0.0.0:8000

google_analytics:
  - 'UA-75822605-1'
  - 'auto'

# Repository
repo_name: 'skale-me/skale'
repo_url: 'https://github.com/skale-me/skale/'

# Copyright
copyright: 'Copyright &copy; 2016 Luca-SAS'

# Configuration
theme:
  name: 'material'
  langage: 'en'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto mono'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/skale-me'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Content
docs_dir: docs

pages:
  - About Skale: 'index.md'
  - Programming guide:
    - 'concepts.md'
    - 'skale-API.md'
    - 'machine-learning.md'
  - 'skale-hackers-guide.md'
